### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by ImJoke** [shelld3v/JSshell#18]
I am using chrome with version 109.0.5414.75 (Official Build) (64-bit) on Windows 11, here is the error message:

![image](https://user-images.githubusercontent.com/55929550/214022405-b509a4d6-a8cf-45ab-beb1-50c9c35b542a.png)

**Comment by shelld3v** [comment]
That's because the website has CSP, I can do nothing about this, the script just doesn't work with websites that have strict CSP
