### ISSUE TITLE
The elif line 109 is broken

### ISSUE THREAD

**Issue by Darkcast** [shelld3v/JSshell#4]
JSshell-master python3 jsh.py -g -w 20
  File "/Users/thedude/Downloads/JSshell-master/jsh.py", line 109
    elif buffer = 'snippet':

also the read me needs to be update

**Comment by shelld3v** [comment]
HI, I have already added it to README =)

**Comment by shelld3v** [comment]
Fixed

**Comment by Darkcast** [comment]
Thank you sir
